services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API=${NEXT_PUBLIC_API}
        - NEXT_PUBLIC_TEST_API=${NEXT_PUBLIC_TEST_API}
        - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
        - NEXT_PUBLIC_TEST_SITE_URL=${NEXT_PUBLIC_TEST_SITE_URL}
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API=${NEXT_PUBLIC_API}
      - NEXT_PUBLIC_TEST_API=${NEXT_PUBLIC_TEST_API}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
      - NEXT_PUBLIC_TEST_SITE_URL=${NEXT_PUBLIC_TEST_SITE_URL}
    expose:
      - '3000'
    restart: unless-stopped
    networks:
      - web

  web-nginx:
    image: nginx:alpine
    ports:
      - '8888:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - next-app
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true
    name: mirtraveler_backend_default
