import { HotOfferAd } from "@/features/api/site/ads";

export const mockHotOffers: HotOfferAd[] = [
  {
    id: "1",
    category_type: "excursion", // или другой enum из вашего проекта
    title: "Премиум отель в Сочи с видом на море",
    address: {
      full_address: "Сочи, ул. Приморская, 15",
      city: "Сочи",
      region: "Краснодарский край",
    },
    rating: 4.8,
    photos: [],
    is_favorite: true,
    room_count: 2,
    rent_type: "сутки",
    guests: 4,
    is_studio: false,
    sleep_place_count: 3,
    price_per_day: 7500,
    average_bill: 2500,
    is_last_minute_tour: 1,
    is_delivery: false,
    link: "/hotels/sochi-premium",
  },
  {
    id: "2",
    category_type: "housing", // или другой enum
    title: "Горный тур в Приэльбрусье",
    address: {
      full_address: "Кабардино-Балкария, Приэльбрусье",
      city: "Терскол",
      region: "Кабардино-Балкария",
    },
    rating: 4.9,
    photos: [],
    is_favorite: false,
    guests: 6,
    price_per_tour: 25000,
    average_bill: 3500,
    is_last_minute_tour: 1,
    is_delivery: true,
    link: "/tours/elbrus-tour",
  },
  {
    id: "3",
    category_type: "transport",
    title: "Студия в центре Москвы",
    address: {
      full_address: "Москва, ул. Тверская, 25",
      city: "Москва",
      region: "Московская область",
    },
    rating: 4.5,
    photos: [],
    is_favorite: true,
    room_count: 1,
    rent_type: "сутки",
    guests: 2,
    is_studio: true,
    sleep_place_count: 2,
    price_per_day: 4500,
    price_per_hour: 800,
    average_bill: 2000,
    is_last_minute_tour: 0,
    is_delivery: true,
    link: "/apartments/moscow-studio",
  },
];
